### PR TITLE
hosts file in yaml language

### PR DESCRIPTION
**Pull request by bcdiaconu**

### CODE REVIEW

**Comment by bcdiaconu** [comment]
I find it less prone to errors to have the `:children` suffix of `.ini` format in a more structured way. Also it makes simpler to create further children and, by this, create a simpler to maintain file when hosts numbers grow up.

A sample here:
https://docs.ansible.com/ansible/latest/inventory_guide/intro_inventory.html#inheriting-variable-values-group-variables-for-groups-of-groups

**Comment by SK1Y101** [comment]
The exact method of supplying hosts to the playbooks (`ini` or `yaml`) is entirely up to the user.
Presumably we should have both as an example structure in the readme to allow users to choose whichever they prefer, rather than supplying either of them in the repo.

**Comment by bcdiaconu** [comment]
@SK1Y101 modified as per your comment

**Review by SK1Y101 — APPROVED** [review]
Awesome, LGTM

**Comment by bcdiaconu** [comment]
looks like also a maintainer needs to approve too

**Pull request merged**
