### PR TITLE
Fixes for ha postgresql

### PR DESCRIPTION
**Pull request by alexsander-souza**
- fix PAF setup
- fix pgsql replication
- add Fencing configuration

### CODE REVIEW

**Comment by alexsander-souza** [comment]
Screenshot from 2023-03-24 18-41-29

**Comment by alexsander-souza** [comment]
Screenshot from 2023-03-24 18-40-42

**Review by cpg1111 — CHANGES_REQUESTED** [review]
I don't quite understand what issue this is fixing, but beyond that, a couple of issues commented.

**Comment by cpg1111** [comment]
@alexsander-souza can we close this now that #108 and #109 have landed?

**Pull request closed without merging**
